[package]
name = "flashcard"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.43.0"
axum = "0.8.1"
sea-orm = { version = "1.1.6", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
