//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod answers;
pub mod questions;
pub mod quiz_question_answers;
pub mod quiz_questions;
pub mod quizes;
pub mod sea_orm_active_enums;
pub mod sets;
pub mod shared_quizes;
pub mod shared_sets;
pub mod test_results;
pub mod test_states;
pub mod tests;
pub mod users;
