//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::{
    answers::Entity as Answers, questions::Entity as Questions,
    quiz_question_answers::Entity as QuizQuestionAnswers, quiz_questions::Entity as QuizQuestions,
    quizes::Entity as Quizes, sets::Entity as Sets, shared_quizes::Entity as SharedQuizes,
    shared_sets::Entity as SharedSets, test_results::Entity as TestResults,
    test_states::Entity as TestStates, tests::Entity as Tests, users::Entity as Users,
};
