//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::answers::Entity as Answers;
pub use super::questions::Entity as Questions;
pub use super::quiz_question_answers::Entity as QuizQuestionAnswers;
pub use super::quiz_questions::Entity as QuizQuestions;
pub use super::quizes::Entity as Quizes;
pub use super::sets::Entity as Sets;
pub use super::shared_quizes::Entity as SharedQuizes;
pub use super::shared_sets::Entity as SharedSets;
pub use super::test_results::Entity as TestResults;
pub use super::test_states::Entity as TestStates;
pub use super::tests::Entity as Tests;
pub use super::users::Entity as Users;
