//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use {
    super::sea_orm_active_enums::QuestionTypeEnum,
    sea_orm::entity::prelude::*,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "questions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub r#type: QuestionTypeEnum,
    pub content: String,
    pub answers: Json,
    pub set_id: Uuid,
    pub creator_id: Uuid,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub is_deleted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::quiz_questions::Entity")]
    QuizQuestions,
    #[sea_orm(
        belongs_to = "super::sets::Entity",
        from = "Column::SetId",
        to = "super::sets::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Sets,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatorId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::quiz_questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuizQuestions.def()
    }
}

impl Related<super::sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sets.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
