//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use {
    sea_orm::entity::prelude::*,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "quiz_question_answers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub quiz_question_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub answer_content: String,
    pub is_answer: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub is_deleted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::quiz_questions::Entity",
        from = "Column::QuizQuestionId",
        to = "super::quiz_questions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    QuizQuestions,
}

impl Related<super::quiz_questions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuizQuestions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
